import os

API_KEY = os.getenv("BINANCE_API_KEY_REAL")
API_SECRET = os.getenv("BINANCE_API_SECRET_REAL")

USE_DEM0 = False

PERCENTUAL_SALDO_POR_ENTRADA = 0.95
STOP_LOSS_PERCENTUAL = 0.02
TAKE_PROFIT_PERCENTUAL = 0.04
RSI_COMPRA_MIN = 40
RSI_COMPRA_MAX = 65

SENDER_EMAIL = os.getenv("BOT_EMAIL_ADRESS")
SENDER_PASSWORD = os.getenv("BOT_16_PASSWORD")
RECEIVER_EMAIL = os.getenv("PERSONAL_EMAIL")
